included: # paths to include during linting. `--path` is ignored if present.
  - Sources
line_length: 140
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji)
identifier_name:
  excluded: # excluded via string array
    - id